version: "3.5"

services:
  api01: &api
    image: lclpedro/rinhabackend2024:latest
    ports:
      - "8081:3000"
    environment:
      - DB_HOSTNAME=db
    networks:
      - fsociety
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.3"
          memory: "30MB"

  api02:
    <<: *api
    ports:
      - "8082:3000"

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api01
        - api02
      ports:
        - "9999:9999"
      networks:
        - fsociety
      deploy:
        resources:
          limits:
            cpus: "0.3"
            memory: "20MB"

  db:
    image: mysql:latest
    volumes:
      - ./data/data.sql:/docker-entrypoint-initdb.d/scripts.sql
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bancocentral
    ports:
      - 3306:3306
    restart: always
    networks:
      - fsociety
    deploy:
      resources:
        limits:
          cpus: "0.9"
          memory: "500MB"

networks:
  fsociety:
    driver: bridge