version: "3.5"

services:
  api01: &api
    image: lclpedro/rinhabackend2024:latest
    ports:
      - "8081:3000"
    environment:
      - DB_HOSTNAME=db
    networks:
      - fsociety
    restart: always
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: "0.4"
          memory: "130MB"

  api02:
    <<: *api 
    environment:
      - DB_HOSTNAME=db
    ports:
      - "8082:3000"
    networks:
      - fsociety

  nginx:
      image: nginx:latest
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - api01
        - api02
      ports:
        - "9999:9999"
      restart: always
      networks:
        - fsociety
      deploy:
        resources:
          limits:
            cpus: "0.1"
            memory: "20MB"

  db:
    image: postgres:12
    volumes:
      - ./data/data.sql:/docker-entrypoint-initdb.d/scripts.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bancocentral
    ports:
      - 5432:5432
    restart: always
    networks:
      - fsociety
    command: ["postgres", "-c", "max_connections=1000", "-c", "shared_buffers=500MB"]
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: "400MB"

networks:
  fsociety:
    driver: bridge